(()=>{
const SESSION_KEY='rwa_demo_session',USER_KEY='rwa_demo_user',PROFILE_KEY='rwa_demo_profile',PREF_KEY='rwa_ui_preferences';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const session=read(SESSION_KEY);
if(!session){location.replace('login.html?return='+encodeURIComponent(location.pathname.split('/').pop()+location.search));return}
const user=read(USER_KEY)||session,profile=read(PROFILE_KEY)||{};
const name=profile.name||user.name||session.name||'RWA Member',email=profile.email||user.email||session.email||'member@rwa.ms';
const initials=name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'RW';
const page=document.body.dataset.accountPage||'overview';
$$('[data-account-name]').forEach(el=>el.textContent=name);$$('[data-account-email]').forEach(el=>el.textContent=email);$$('[data-account-avatar]').forEach(el=>el.textContent=initials);
$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===page));
const topSearch=$('#account-search');if(topSearch){const q=new URLSearchParams(location.search).get('q')||'';if(page==='portfolio')topSearch.value=q;topSearch.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();location.href='portfolio.html?q='+encodeURIComponent(topSearch.value.trim())}})}
let toastTimer;function toast(msg){let el=$('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
window.RWA_UI_TOAST=toast;
$$('[data-logout]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();location.href='logout.html'}));
$$('[data-ui-only]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();toast(el.dataset.message||'UI is ready for backend connection.')}));
const catalog=window.RWA_CATALOG||[];
const holdings=[
 {key:'property-1',units:'18.40%',value:'$86,400',change:'+8.7%',cost:'$79,480'},
 {key:'ai-models-1',units:'12 licenses',value:'$28,800',change:'+14.2%',cost:'$25,200'},
 {key:'marketplace-1',units:'24 units',value:'$7,680',change:'+3.1%',cost:'$7,450'},
 {key:'franchise-1',units:'0.55%',value:'$9,900',change:'+6.5%',cost:'$9,295'},
 {key:'apps-1',units:'8 licenses',value:'$6,240',change:'+11.8%',cost:'$5,580'},
 {key:'games-1',units:'6 plots',value:'$2,700',change:'-1.4%',cost:'$2,738'}
];
const txs=[
 {id:'RWA-78421',type:'Purchase',asset:'Seaview Residence',category:'Property',amount:'$12,000',date:'Sep 10, 2026 · 14:26',status:'Completed',icon:'fa-building'},
 {id:'RWA-78409',type:'Income',asset:'BrewLab Cafe',category:'Franchise',amount:'+$186',date:'Sep 9, 2026 · 09:42',status:'Completed',icon:'fa-store'},
 {id:'RWA-78372',type:'Purchase',asset:'Alpha Trader Model',category:'AI Models',amount:'$2,400',date:'Sep 8, 2026 · 20:15',status:'Completed',icon:'fa-brain'},
 {id:'RWA-78311',type:'Deposit',asset:'USD Wallet',category:'Wallet',amount:'+$5,000',date:'Sep 7, 2026 · 11:03',status:'Completed',icon:'fa-wallet'},
 {id:'RWA-78288',type:'Transfer',asset:'LedgerFlow',category:'Apps',amount:'$780',date:'Sep 6, 2026 · 17:20',status:'Pending',icon:'fa-arrow-right-arrow-left'},
 {id:'RWA-78190',type:'Order',asset:'Origins Land Plot',category:'Games',amount:'$900',date:'Sep 5, 2026 · 15:10',status:'Cancelled',icon:'fa-gamepad'}
];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const product=k=>catalog.find(p=>p.key===k)||catalog[0];
function renderOpportunities(){const root=$('#account-opportunities');if(!root)return;root.innerHTML=holdings.slice(0,4).map(h=>{const p=product(h.key);return `<a class="portfolio-card" href="asset-detail.html?asset=${encodeURIComponent(p.key)}"><img src="${p.image}" alt="${esc(p.name)}"><div class="pc-body"><b>${esc(p.name)}</b><small>${esc(p.brand)} · ${esc(p.label)}</small><strong>${esc(p.price)}</strong><div class="pc-meta"><span>${esc(p.holders)}</span><span class="positive">${p.sold}% sold</span></div></div></a>`}).join('')}
function renderPortfolio(){const tbody=$('#portfolio-table-body'),mobile=$('#portfolio-mobile');if(!tbody&&!mobile)return;const params=new URLSearchParams(location.search),q=(params.get('q')||'').toLowerCase();let filter='all';const buttons=$$('[data-portfolio-filter]');function draw(){let list=holdings.filter(h=>{const p=product(h.key);return (filter==='all'||p.category===filter)&&(!q||`${p.name} ${p.brand} ${p.label}`.toLowerCase().includes(q))});if(tbody)tbody.innerHTML=list.map(h=>{const p=product(h.key),neg=h.change.startsWith('-');return `<tr><td><a class="asset-cell" href="asset-detail.html?asset=${p.key}" style="text-decoration:none"><img src="${p.image}" alt=""><span><b>${esc(p.name)}</b><small>${esc(p.brand)} · ${esc(p.label)}</small></span></a></td><td>${esc(h.units)}</td><td><b>${esc(h.value)}</b></td><td>${esc(h.cost)}</td><td class="${neg?'negative':'positive'}"><b>${esc(h.change)}</b></td><td><a class="panel-link" href="asset-detail.html?asset=${p.key}">View asset →</a></td></tr>`}).join('')||'<tr><td colspan="6"><div class="empty-state">No holdings match this filter.</div></td></tr>';if(mobile)mobile.innerHTML=list.map(h=>{const p=product(h.key),neg=h.change.startsWith('-');return `<a class="portfolio-card" href="asset-detail.html?asset=${p.key}"><img src="${p.image}" alt="${esc(p.name)}"><div class="pc-body"><b>${esc(p.name)}</b><small>${esc(p.label)} · ${esc(h.units)}</small><strong>${esc(h.value)}</strong><div class="pc-meta"><span>${esc(p.price)}</span><span class="${neg?'negative':'positive'}">${esc(h.change)}</span></div></div></a>`}).join('')||'<div class="empty-state">No holdings match.</div>'}
buttons.forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.portfolioFilter||'all';buttons.forEach(x=>x.classList.toggle('active',x===b));draw()}));draw()}
function renderAssetDetail(){const root=$('#asset-detail');if(!root)return;const key=new URLSearchParams(location.search).get('asset')||'property-1',p=product(key),h=holdings.find(x=>x.key===p.key);root.innerHTML=`<div class="detail-hero"><div class="detail-media"><img src="${p.image}" alt="${esc(p.name)}"></div><div class="detail-copy"><div class="eyebrow">${esc(p.label)} · RWA Asset</div><h1>${esc(p.name)}</h1><div class="detail-brand">${esc(p.brand)} · ${esc(p.holders)}</div><div class="detail-price">${esc(p.price)}</div><span class="status-pill"><i class="fa-solid fa-shield-halved"></i> UI verified state</span><div class="detail-facts"><div class="detail-fact"><small>Your position</small><b>${esc(h?.units||'Not owned')}</b></div><div class="detail-fact"><small>Portfolio value</small><b>${esc(h?.value||'—')}</b></div><div class="detail-fact"><small>Offering progress</small><b>${p.sold}% sold</b></div></div><div class="order-box"><h3>Transaction preview</h3><div class="order-line"><span>Asset</span><b>${esc(p.name)}</b></div><div class="order-line"><span>Reference price</span><b>${esc(p.price)}</b></div><div class="order-line"><span>Execution</span><b>Backend connection required</b></div><div style="display:flex;gap:8px;margin-top:10px"><a class="btn primary" href="transaction-detail.html?mode=preview&asset=${p.key}">Review transaction <i class="fa-solid fa-arrow-right"></i></a><a class="btn" href="portfolio.html">Back to portfolio</a></div></div><p class="account-page-note">This screen is UI-only. It does not place orders, transfer funds, or create on-chain ownership.</p></div></div>`}
function renderTransactions(){const root=$('#transaction-list');if(!root)return;let status='all';const buttons=$$('[data-tx-filter]');function draw(){const list=txs.filter(t=>status==='all'||t.status.toLowerCase()===status);root.innerHTML=list.map(t=>`<a class="transaction-row" href="transaction-detail.html?id=${t.id}"><span class="tx-icon"><i class="fa-solid ${t.icon}"></i></span><div><b>${esc(t.type)} · ${esc(t.asset)}</b><small>${esc(t.id)} · ${esc(t.category)}</small></div><div><b>${esc(t.amount)}</b><small>Amount</small></div><div><b>${esc(t.date.split(' · ')[0])}</b><small>${esc(t.date.split(' · ')[1]||'')}</small></div><div><span class="badge ${t.status==='Completed'?'success':t.status==='Pending'?'pending':t.status==='Cancelled'?'failed':''}">${esc(t.status)}</span></div><i class="fa-solid fa-chevron-right" style="font-size:8px;color:#9ba7b2"></i></a>`).join('')||'<div class="empty-state">No transactions in this status.</div>'}buttons.forEach(b=>b.addEventListener('click',()=>{status=b.dataset.txFilter;buttons.forEach(x=>x.classList.toggle('active',x===b));draw()}));draw()}
function renderTransactionDetail(){const root=$('#transaction-detail');if(!root)return;const q=new URLSearchParams(location.search),mode=q.get('mode'),assetKey=q.get('asset'),id=q.get('id');let t=txs.find(x=>x.id===id);if(mode==='preview'){const p=product(assetKey||'property-1');t={id:'PREVIEW',type:'Purchase preview',asset:p.name,category:p.label,amount:p.price,date:'Not submitted',status:'UI Preview',icon:'fa-bag-shopping',assetKey:p.key}}if(!t)t=txs[0];root.innerHTML=`<div class="two-col"><section class="panel"><div class="panel-head"><div><h2>${esc(t.type)}</h2><p>${esc(t.id)}</p></div><span class="badge ${t.status==='Completed'?'success':t.status==='Pending'?'pending':t.status==='Cancelled'?'failed':''}">${esc(t.status)}</span></div><div class="panel-body"><div class="order-line"><span>Asset</span><b>${esc(t.asset)}</b></div><div class="order-line"><span>Category</span><b>${esc(t.category)}</b></div><div class="order-line"><span>Amount</span><b>${esc(t.amount)}</b></div><div class="order-line"><span>Date</span><b>${esc(t.date)}</b></div><div class="order-line"><span>Reference</span><b>${esc(t.id)}</b></div><div class="divider"></div><div style="display:flex;gap:8px;flex-wrap:wrap"><a class="btn" href="transactions.html">All transactions</a>${t.assetKey?`<a class="btn soft" href="asset-detail.html?asset=${t.assetKey}">View asset</a>`:''}<button class="btn primary" data-ui-only data-message="Transaction submission belongs to the backend agent.">Continue <i class="fa-solid fa-arrow-right"></i></button></div></div></section><section class="panel"><div class="panel-head"><div><h2>Activity timeline</h2><p>UI state representation</p></div></div><div class="panel-body"><div class="timeline"><div class="timeline-item"><b>Transaction prepared</b><small>${esc(t.date)}</small></div><div class="timeline-item ${t.status==='Pending'||t.status==='UI Preview'?'pending':''}"><b>${t.status==='Completed'?'Processing completed':'Awaiting backend execution'}</b><small>${t.status==='Completed'?'Preview receipt available.':'No network action has been submitted.'}</small></div>${t.status==='Completed'?'<div class="timeline-item"><b>Portfolio updated</b><small>UI history reflects the completed state.</small></div>':''}</div></div></section></div>`;$$('[data-ui-only]',root).forEach(el=>el.addEventListener('click',e=>{e.preventDefault();toast(el.dataset.message)}))}
function initProfile(){const form=$('#profile-form');if(!form)return;const fields={name,email,phone:profile.phone||'',country:profile.country||'Indonesia',city:profile.city||'',investor:profile.investor||'Individual'};Object.entries(fields).forEach(([k,v])=>{const el=$(`[name="${k}"]`,form);if(el)el.value=v});form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());write(PROFILE_KEY,data);const u=read(USER_KEY)||{};write(USER_KEY,{...u,name:data.name,email:data.email});toast('Profile UI preferences saved in this browser.');setTimeout(()=>location.reload(),550)})}
function initSettings(){const prefs=read(PREF_KEY)||{language:'English',currency:'USD',compact:false,emails:true,priceAlerts:true};$$('[data-pref-switch]').forEach(btn=>{const key=btn.dataset.prefSwitch;btn.classList.toggle('on',!!prefs[key]);btn.addEventListener('click',()=>{prefs[key]=!prefs[key];btn.classList.toggle('on',prefs[key]);write(PREF_KEY,prefs);toast('Preference saved locally.')})});$$('[data-pref-select]').forEach(sel=>{const key=sel.dataset.prefSelect;if(prefs[key])sel.value=prefs[key];sel.addEventListener('change',()=>{prefs[key]=sel.value;write(PREF_KEY,prefs);toast('Preference saved locally.')})})}
function initSecurity(){const prefs=read('rwa_security_ui')||{twofa:false,passkey:false,loginAlerts:true};$$('[data-security-switch]').forEach(btn=>{const key=btn.dataset.securitySwitch;btn.classList.toggle('on',!!prefs[key]);btn.addEventListener('click',()=>{prefs[key]=!prefs[key];btn.classList.toggle('on',prefs[key]);write('rwa_security_ui',prefs);toast(`${key==='twofa'?'2FA':key==='passkey'?'Passkey':'Login alerts'} UI ${prefs[key]?'enabled':'disabled'}. Backend hookup still required.`)})})}
function initWallet(){const modal=$('#wallet-modal'),title=$('#wallet-modal-title'),mode=$('#wallet-mode');function open(label){if(!modal)return;title.textContent=label;mode.textContent=label==='Add funds'?'Deposit funds':'Withdraw funds';modal.classList.add('open')}$$('[data-wallet-action]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.walletAction)));$$('[data-modal-close]').forEach(b=>b.addEventListener('click',()=>modal?.classList.remove('open')));modal?.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});$('#wallet-preview-submit')?.addEventListener('click',e=>{e.preventDefault();toast('Wallet action is UI-only; no funds were moved.');modal?.classList.remove('open')})}
renderOpportunities();renderPortfolio();renderAssetDetail();renderTransactions();renderTransactionDetail();initProfile();initSettings();initSecurity();initWallet();
})();
