from pathlib import Path
from PIL import Image
R=Path(__file__).resolve().parent
A=R/'assets'; A.mkdir(exist_ok=True)
desk=Image.open(R/'desktop-reference.png').convert('RGB')
mob=Image.open(R/'mobile-reference.png').convert('RGB')
def crop(im,box,name):
    p=A/name; im.crop(box).save(p,quality=95,subsampling=0) if p.suffix.lower()=='.jpg' else im.crop(box).save(p); return name
logo=crop(desk,(20,8,182,62),'logo.png')
hero=crop(desk,(720,72,1025,354),'hero-person.jpg')
hero_m=crop(mob,(450,177,800,503),'hero-person-mobile.jpg')
cat_market=crop(desk,(385,403,676,585),'cat-marketplace.jpg')
cat_property=crop(desk,(805,402,1133,585),'cat-property.jpg')
cat_games=crop(desk,(1270,402,1625,585),'cat-games.jpg')
for name,box in {'heel.jpg':(250,644,454,742),'shoe.jpg':(480,644,682,742),'polo.jpg':(707,644,905,742),'serum.jpg':(931,644,1133,742),'residence.jpg':(1160,644,1362,742),'land.jpg':(1385,644,1591,742)}.items(): crop(desk,box,name)
products=[('heel.jpg','Velora Heel','Luxe Studios','Marketplace','$320','3,248','65'),('shoe.jpg','Nimble One','Aeroic Collection','Marketplace','$180','1,929','38'),('polo.jpg','Classic Polo','RWA Apparel','Marketplace','$150','2,530','78'),('serum.jpg','Aurora Glow Serum','Lumiere Beauty','Marketplace','$95','4,120','78'),('residence.jpg','Seaview Residence','Aurea Living','Property','$120,000','438','72'),('land.jpg','Origins Land Plot','WorldReal Estates','Games','$450','2,310','49')]
desktop_css=(R/'desktop.css').read_text(); mobile_css=(R/'mobile.css').read_text()
fa='<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">'
def card(p):
    img,name,brand,kind,price,holders,sold=p
    return f'''<article class="asset-card"><div class="discount">Up to 70% Off<br>for Holders</div><button class="heart"><i class="fa-regular fa-heart"></i></button><img src="assets/{img}" alt=""><h4>{name}</h4><p>{brand} <span>| {kind}</span></p><strong>{price}</strong><div class="holders"><span>●●●●</span><small>{holders} holders</small></div><div class="sold"><i style="--p:{sold}%"></i><span>SOLD {sold}%</span></div><button class="detail"><i class="fa-solid fa-cart-shopping"></i>View Details</button></article>'''
asset_cards=''.join(card(p) for p in products)
sidebar_market="".join([f'<a><i class="fa-solid fa-circle"></i>{x}</a>' for x in ["Women's Clothing","Shoes","Men's Clothing","Bags & Luggage","Beauty & Health"]])
sidebar_prop="".join([f'<a><i class="fa-regular fa-building"></i>{x}</a>' for x in ["TownHouse","Rumah Sakit","Apartment & Condomin","Villa & Resort","Hotel","Office Tower","Kawasan Industri","Mixed Use Development"]])
sidebar_games="".join([f'<a><i class="fa-solid fa-gamepad"></i>{x}</a>' for x in ["Game Land","Characters","Weapons","Skins","Loot Boxes","Game Tokens","Esports Assets","Metaverse Assets"]])
chart='''<svg class="chart" viewBox="0 0 420 100" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#62d49f" stop-opacity=".45"/><stop offset="1" stop-color="#62d49f" stop-opacity=".05"/></linearGradient></defs><path d="M4 84L22 78 38 74 50 77 64 69 78 72 94 66 108 71 126 64 140 74 154 67 168 72 182 63 198 59 214 66 230 54 246 57 261 49 278 38 294 45 309 39 324 42 338 31 354 35 368 24 383 29 399 16 416 5V100H4Z" fill="url(#area)"/><polyline points="4,84 22,78 38,74 50,77 64,69 78,72 94,66 108,71 126,64 140,74 154,67 168,72 182,63 198,59 214,66 230,54 246,57 261,49 278,38 294,45 309,39 324,42 338,31 354,35 368,24 383,29 399,16 416,5" fill="none" stroke="#008b62" stroke-width="2.2"/></svg>'''
desktop=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RWA.ms Desktop</title>{fa}<style>{desktop_css}</style></head><body><div class="page">
<header class="topbar" data-ai-zone="desktop.header"><a class="brand"><img src="assets/logo.png"></a><label class="search"><i class="fa-solid fa-magnifying-glass"></i><input placeholder="Search assets, properties, games, collections, or brands..."></label><nav class="mainnav"><a>Marketplace</a><a>Property</a><a>Games</a><a>RWA Token</a><a>Community</a><a>Learn</a></nav><button class="lang"><i class="fa-solid fa-globe"></i> EN <i class="fa-solid fa-chevron-down"></i></button><button class="cart"><i class="fa-solid fa-cart-shopping"></i><span>0</span></button><button class="signin">Sign In</button><button class="join">Join RWA.ms</button></header>
<div class="shell"><aside class="sidebar" data-ai-zone="desktop.sidebar"><section class="side-group"><div class="side-title"><span><i class="fa-solid fa-bag-shopping"></i>Marketplace</span><i class="fa-solid fa-chevron-up"></i></div>{sidebar_market}</section><section class="side-group"><div class="side-title"><span><i class="fa-solid fa-building"></i>Property</span><i class="fa-solid fa-chevron-up"></i></div>{sidebar_prop}</section><section class="side-group"><div class="side-title"><span><i class="fa-solid fa-gamepad"></i>Games</span><i class="fa-solid fa-chevron-up"></i></div>{sidebar_games}</section><a class="side-simple"><i class="fa-solid fa-shield-halved"></i>Verified Assets<i class="fa-solid fa-chevron-right"></i></a><a class="side-simple"><i class="fa-solid fa-headset"></i>24/7 Support<i class="fa-solid fa-chevron-right"></i></a><a class="side-simple"><i class="fa-solid fa-book-open"></i>Learn & Discover<i class="fa-solid fa-chevron-right"></i></a><div class="side-promo"><i class="fa-solid fa-leaf"></i><div><b>Real Assets.<br>A Brighter Tomorrow.</b><small>Invest. Own. Grow.</small></div><i class="fa-solid fa-arrow-right"></i></div></aside>
<main class="content"><div class="hero-row"><section class="hero" data-ai-zone="desktop.hero"><div class="hero-copy"><div class="eyebrow">OWN • INVEST • TRADE • LIVE REAL</div><h1>Iconic Assets.<br>Real Ownership.</h1><p>Invest in tokenized fashion, property, and gaming assets<br>from the world's most coveted real assets. Diversify. Own. Grow.</p><button>Shop Marketplace <i class="fa-solid fa-arrow-right-long"></i></button></div><div class="hero-visual"><img src="assets/hero-person.jpg"><div class="hero-mask"></div></div><div class="hero-right"><span>TIMELESS.<br>ASSETS.<br>TANGIBLE<br>OPPORTUNITIES.</span><b>RWA.ms</b><em>A More<br>Real Tomorrow</em></div><div class="hero-benefits"><span><i class="fa-solid fa-globe"></i>Global Real Assets</span><span><i class="fa-solid fa-chart-simple"></i>Real Utility</span><span><i class="fa-solid fa-people-group"></i>Growing Community</span><span><i class="fa-solid fa-shield-halved"></i>Trusted & Regulated</span><span><i class="fa-solid fa-leaf"></i>A More Real Tomorrow</span></div></section>
<section class="topchart" data-ai-zone="desktop.chart"><div class="chart-head"><div><h2>Top Chart</h2><p>RWA Token (24h)</p></div><div class="ranges"><button class="active">1D</button><button>1W</button><button>1M</button><button>1Y</button><button>ALL</button></div></div><div class="price-row"><strong>$0.1256</strong><span>+12.4% <i class="fa-solid fa-arrow-up"></i></span></div><p class="delta">+ $0.0138 in the last 24 hours</p>{chart}<div class="stat-grid"><div><i class="fa-solid fa-arrow-trend-up"></i><span>Top Gainers</span><strong>+18</strong><b>+28.6%</b><small>of 100 tokens</small></div><div><i class="fa-solid fa-chart-simple"></i><span>24h Volume</span><strong>$12.4M</strong><b>+35.2%</b><small>vs. previous day</small></div><div><i class="fa-solid fa-users"></i><span>Active Holders</span><strong>8,452</strong><b>+16.8%</b><small>unique wallets</small></div></div></section></div>
<section class="verticals" data-ai-zone="desktop.verticals"><article class="vertical"><div class="v-copy"><i class="fa-solid fa-bag-shopping"></i><h3>Marketplace</h3><p>Iconic fashion, beauty and lifestyle brands, now tokenized.</p><button>Explore Marketplace <i class="fa-solid fa-arrow-right"></i></button></div><img src="assets/cat-marketplace.jpg"></article><article class="vertical"><div class="v-copy"><i class="fa-solid fa-building"></i><h3>Property</h3><p>Tokenized real estate from residential to commercial.</p><button>Explore Property <i class="fa-solid fa-arrow-right"></i></button></div><img src="assets/cat-property.jpg"></article><article class="vertical"><div class="v-copy"><i class="fa-solid fa-gamepad"></i><h3>Games</h3><p>Own legendary in-game assets in the real world.</p><button>Explore Games <i class="fa-solid fa-arrow-right"></i></button></div><img src="assets/cat-games.jpg"></article></section>
<section class="featured" data-ai-zone="desktop.featured"><div class="featured-head"><h2>Featured Assets</h2><div class="tabs"><button class="active">All Assets</button><button>Marketplace</button><button>Property</button><button>Games</button></div><div class="viewall">View All <i class="fa-solid fa-arrow-right"></i><button><i class="fa-solid fa-chevron-left"></i></button><button><i class="fa-solid fa-chevron-right"></i></button></div></div><div class="asset-grid">{asset_cards}</div></section>
<footer class="trustbar" data-ai-zone="desktop.footer"><div class="trust-note"><i class="fa-solid fa-shield-halved"></i><span>RWA.ms is building a more accessible, transparent, and prosperous<br>real asset economy for a brighter tomorrow.</span></div><div><i class="fa-solid fa-shield-halved"></i><b>Verified & Secure</b><small>Institutional grade security</small></div><div><i class="fa-solid fa-people-group"></i><b>50,000+ Investors</b><small>Growing together</small></div><div><i class="fa-solid fa-chart-simple"></i><b>128+ Projects</b><small>Across asset classes</small></div><div><i class="fa-solid fa-globe"></i><b>33+ Countries</b><small>Global impact</small></div><button>Start Investing Today <i class="fa-solid fa-arrow-right"></i></button></footer></main></div></div>
<script>document.querySelectorAll('.ranges button,.tabs button').forEach(b=>b.onclick=()=>{{[...b.parentElement.children].forEach(x=>x.classList.remove('active'));b.classList.add('active')}});document.querySelectorAll('.heart').forEach(b=>b.onclick=()=>{{b.classList.toggle('liked');b.querySelector('i').className=b.classList.contains('liked')?'fa-solid fa-heart':'fa-regular fa-heart'}})</script></body></html>'''
(R/'desktop.html').write_text(desktop)
def mcard(p):
    img,name,brand,kind,price,holders,sold=p
    return f'''<article><button class="heart"><i class="fa-regular fa-heart"></i></button><img src="assets/{img}"><h4>{name}</h4><p>{brand}</p><strong>{price}</strong><div><span>●●●●</span><small>{holders} holders</small></div><div class="m-sold"><i style="--p:{sold}%"></i><span>SOLD {sold}%</span></div></article>'''
m_cards=''.join(mcard(p) for p in products[:4])
m_chart='''<svg class="m-line" viewBox="0 0 820 115" preserveAspectRatio="none"><defs><linearGradient id="marea" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#58d39a" stop-opacity=".48"/><stop offset="1" stop-color="#58d39a" stop-opacity=".06"/></linearGradient></defs><path d="M320 105L350 95 376 89 401 93 430 87 455 90 480 78 508 82 534 68 562 74 590 58 618 60 648 49 674 36 703 42 730 30 758 34 784 17 812 7V115H320Z" fill="url(#marea)"/><polyline points="320,105 350,95 376,89 401,93 430,87 455,90 480,78 508,82 534,68 562,74 590,58 618,60 648,49 674,36 703,42 730,30 758,34 784,17 812,7" fill="none" stroke="#008b62" stroke-width="3"/></svg>'''
mobile=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RWA.ms Mobile</title>{fa}<style>{mobile_css}</style></head><body><div class="mobile-page">
<header class="m-head" data-ai-zone="mobile.header"><img src="assets/logo.png"><div class="m-lang"><i class="fa-solid fa-globe"></i><b>EN</b><i class="fa-solid fa-chevron-down"></i></div></header><label class="m-search"><i class="fa-solid fa-magnifying-glass"></i><input placeholder="Search assets, properties, games, collections, or brands..."></label>
<section class="m-hero" data-ai-zone="mobile.hero"><div class="m-hero-copy"><div class="eyebrow">OWN • INVEST • TRADE • LIVE REAL</div><h1>Iconic Assets.<br>Real Ownership.</h1><p>Invest in tokenized fashion, property, and gaming<br>assets from the world's most coveted real assets.<br>Diversify. Own. Grow.</p><button>Shop Marketplace <i class="fa-solid fa-arrow-right-long"></i></button></div><img src="assets/hero-person-mobile.jpg"><div class="m-hero-right"><span>TIMELESS.<br>ASSETS.<br>TANGIBLE<br>OPPORTUNITIES.</span><b>RWA.ms</b><em>A More<br>Real Tomorrow</em></div><div class="dots"><i class="active"></i><i></i><i></i></div></section>
<section class="m-usp" data-ai-zone="mobile.usp"><div><i class="fa-solid fa-globe"></i><span>Global<br>Real Assets</span></div><div><i class="fa-solid fa-chart-simple"></i><span>Real<br>Utility</span></div><div><i class="fa-solid fa-people-group"></i><span>Growing<br>Community</span></div><div><i class="fa-solid fa-shield-halved"></i><span>Trusted &<br>Regulated</span></div></section>
<section class="m-verticals" data-ai-zone="mobile.verticals"><article><img src="assets/cat-marketplace.jpg"><div><i class="fa-solid fa-bag-shopping"></i><h3>Marketplace</h3><p>Iconic fashion, beauty<br>and lifestyle brands,<br>now tokenized.</p><button>Explore <i class="fa-solid fa-arrow-right"></i></button></div></article><article><img src="assets/cat-property.jpg"><div><i class="fa-solid fa-building"></i><h3>Property</h3><p>Tokenized real<br>estate from<br>residential to<br>commercial.</p><button>Explore <i class="fa-solid fa-arrow-right"></i></button></div></article><article><img src="assets/cat-games.jpg"><div><i class="fa-solid fa-gamepad"></i><h3>Games</h3><p>Own legendary<br>in-game assets<br>in the real world.</p><button>Explore <i class="fa-solid fa-arrow-right"></i></button></div></article></section>
<section class="m-chart-card" data-ai-zone="mobile.chart"><div class="m-chart-top"><div><h2>Top Chart</h2><p>RWA Token (24h)</p></div><div class="ranges"><button class="active">1D</button><button>1W</button><button>1M</button><button>1Y</button><button>ALL</button></div></div><div class="m-price"><strong>$0.1256</strong><span>+12.4% <i class="fa-solid fa-arrow-up"></i></span></div><p class="m-delta">+ $0.0138 in the last 24 hours</p>{m_chart}<div class="m-stats"><div><i class="fa-solid fa-arrow-trend-up"></i><span>Top Gainers</span><strong>+18 <b>+28.6%</b></strong><small>of 100 tokens</small></div><div><i class="fa-solid fa-chart-simple"></i><span>24h Volume</span><strong>$12.4M <b>+35.2%</b></strong><small>vs. previous day</small></div><div><i class="fa-solid fa-users"></i><span>Active Holders</span><strong>8,452 <b>+16.8%</b></strong><small>unique wallets</small></div></div></section>
<section class="m-featured" data-ai-zone="mobile.featured"><div class="m-featured-head"><h2>Featured Assets</h2><div class="m-tabs"><button class="active">All Assets</button><button>Marketplace</button><button>Property</button><button>Games</button></div></div><div class="m-assets">{m_cards}</div></section>
<nav class="bottomnav" data-ai-zone="mobile.bottomnav"><button class="active"><i class="fa-solid fa-house"></i><span>Home</span></button><button><i class="fa-solid fa-bag-shopping"></i><span>Marketplace</span></button><button><i class="fa-regular fa-building"></i><span>Property</span></button><button><i class="fa-solid fa-gamepad"></i><span>Game</span></button><button><i class="fa-regular fa-user"></i><span>Account</span></button></nav></div>
<script>document.querySelectorAll('.ranges button,.m-tabs button,.bottomnav button').forEach(b=>b.onclick=()=>{{[...b.parentElement.children].forEach(x=>x.classList.remove('active'));b.classList.add('active')}});document.querySelectorAll('.heart').forEach(b=>b.onclick=()=>{{b.classList.toggle('liked');b.querySelector('i').className=b.classList.contains('liked')?'fa-solid fa-heart':'fa-regular fa-heart'}})</script></body></html>'''
(R/'mobile.html').write_text(mobile)
(R/'index.html').write_text('''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RWA.ms Preview</title><style>body{margin:0;font-family:Arial;background:#06111c;color:white;display:grid;place-items:center;min-height:100vh}.box{text-align:center}.box a{display:inline-block;margin:10px;padding:14px 22px;background:#08775b;color:#fff;text-decoration:none;border-radius:10px;font-weight:700}</style><div class="box"><h1>RWA.ms Screenshot-to-Code Rebuild</h1><a href="desktop.html">Desktop</a><a href="mobile.html">Mobile</a></div>''')
print('BUILT',len(desktop),len(mobile))
