(()=>{
const products=[
 {key:'velora',name:'Velora Heel',brand:'Luxe Studios',category:'marketplace',label:'Marketplace',price:'$320',holders:'3,248 holders',sold:65,image:'assets/heel.jpg'},
 {key:'nimble',name:'Nimble One',brand:'Aeroic Collection',category:'marketplace',label:'Marketplace',price:'$180',holders:'1,929 holders',sold:38,image:'assets/shoe.jpg'},
 {key:'polo',name:'Classic Polo',brand:'RWA Apparel',category:'marketplace',label:'Marketplace',price:'$150',holders:'2,530 holders',sold:78,image:'assets/polo.jpg'},
 {key:'serum',name:'Aurora Glow Serum',brand:'Lumiere Beauty',category:'marketplace',label:'Marketplace',price:'$95',holders:'4,120 holders',sold:78,image:'assets/serum.jpg'},
 {key:'residence',name:'Seaview Residence',brand:'Aurea Living',category:'property',label:'Property',price:'$120,000',holders:'438 holders',sold:72,image:'assets/residence.jpg'},
 {key:'origins',name:'Origins Land Plot',brand:'WorldReal Estates',category:'games',label:'Games',price:'$450',holders:'2,310 holders',sold:49,image:'assets/land.jpg'}
];
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
const featured=qs('.m-featured'), assets=qs('.m-assets'), tabs=qs('.m-tabs');
if(!featured||!assets||!tabs)return;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=p=>`<article class="asset-card" tabindex="0" role="button" aria-label="Open ${esc(p.name)}" data-key="${p.key}" data-category="${p.category}"><button class="heart" aria-label="Save ${esc(p.name)}"><i class="fa-regular fa-heart"></i></button><img src="${p.image}" alt="${esc(p.name)}"><h4>${esc(p.name)}</h4><p>${esc(p.brand)}</p><strong>${p.price}</strong><div><span>●●●●</span><small>${p.holders}</small></div><div class="m-sold"><i style="--p:${p.sold}%"></i><span>SOLD ${p.sold}%</span></div></article>`;
assets.innerHTML=products.map(card).join('');
const empty=document.createElement('div');empty.className='m-empty';empty.textContent='No assets match this filter.';featured.appendChild(empty);
let activeFilter='all';let selected=localStorage.getItem('rwaSelectedAsset')||'';
const sheet=document.createElement('div');sheet.className='asset-sheet';sheet.id='assetSheet';sheet.innerHTML=`<div class="asset-sheet__backdrop"></div><div class="asset-sheet__panel" role="dialog" aria-modal="true" aria-labelledby="assetSheetTitle"><div class="asset-sheet__grab"></div><button class="asset-sheet__close" aria-label="Close">×</button><div class="asset-sheet__hero"><img alt=""><div><div class="asset-sheet__eyebrow"></div><h3 id="assetSheetTitle"></h3><p class="asset-sheet__brand"></p><div class="asset-sheet__price"></div></div></div><div class="asset-sheet__facts"><div class="asset-sheet__fact"><small>Holders</small><b data-fact="holders"></b></div><div class="asset-sheet__fact"><small>Progress</small><b data-fact="sold"></b></div></div><button class="asset-sheet__cta">Select this asset</button></div>`;document.body.appendChild(sheet);
const selBar=document.createElement('div');selBar.className='selection-bar';selBar.innerHTML='<span></span><button type="button">View selected</button>';document.body.appendChild(selBar);
const toast=document.createElement('div');toast.className='mobile-toast';document.body.appendChild(toast);
let current=null,toastTimer;
function notify(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1700)}
function syncSelected(){qsa('.asset-card').forEach(c=>c.classList.toggle('selected',c.dataset.key===selected));const p=products.find(x=>x.key===selected);selBar.classList.toggle('show',!!p);if(p)selBar.querySelector('span').textContent=`Selected: ${p.name}`}
function openProduct(p){current=p;sheet.querySelector('img').src=p.image;sheet.querySelector('img').alt=p.name;sheet.querySelector('.asset-sheet__eyebrow').textContent=p.label;sheet.querySelector('h3').textContent=p.name;sheet.querySelector('.asset-sheet__brand').textContent=p.brand;sheet.querySelector('.asset-sheet__price').textContent=p.price;sheet.querySelector('[data-fact="holders"]').textContent=p.holders;sheet.querySelector('[data-fact="sold"]').textContent=`${p.sold}% sold`;sheet.querySelector('.asset-sheet__cta').textContent=selected===p.key?'Selected ✓':'Select this asset';sheet.classList.add('open');document.body.style.overflow='hidden';sheet.querySelector('.asset-sheet__close').focus()}
function closeSheet(){sheet.classList.remove('open');document.body.style.overflow=''}
function setFilter(filter,scroll=true){activeFilter=filter;const query=(qs('.m-search input')?.value||'').trim().toLowerCase();let visible=0;qsa('.asset-card').forEach(c=>{const p=products.find(x=>x.key===c.dataset.key);const categoryOk=filter==='all'||p.category===filter;const searchOk=!query||`${p.name} ${p.brand} ${p.label}`.toLowerCase().includes(query);c.hidden=!(categoryOk&&searchOk);if(!c.hidden)visible++});empty.classList.toggle('show',visible===0);qsa('.m-tabs button').forEach(b=>b.classList.toggle('active',({"All Assets":'all','Marketplace':'marketplace','Property':'property','Games':'games'}[b.textContent.trim()]||'')===filter));if(scroll){featured.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>{assets.scrollLeft=0},250)}}
qsa('.asset-card').forEach(c=>{c.addEventListener('click',e=>{if(e.target.closest('.heart'))return;openProduct(products.find(p=>p.key===c.dataset.key))});c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProduct(products.find(p=>p.key===c.dataset.key))}})});
qsa('.heart').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();b.classList.toggle('liked');b.querySelector('i').className=b.classList.contains('liked')?'fa-solid fa-heart':'fa-regular fa-heart';notify(b.classList.contains('liked')?'Saved to favorites':'Removed from favorites')}));
qsa('.m-tabs button').forEach(b=>b.addEventListener('click',()=>setFilter(({"All Assets":'all','Marketplace':'marketplace','Property':'property','Games':'games'}[b.textContent.trim()]||'all'),false)));
const search=qs('.m-search input');if(search)search.addEventListener('input',()=>setFilter(activeFilter,false));
qsa('.m-verticals article').forEach((a,i)=>{const f=['marketplace','property','games'][i];const btn=a.querySelector('button');if(btn)btn.addEventListener('click',e=>{e.preventDefault();setFilter(f,true)})});
const heroBtn=qs('.m-hero button');if(heroBtn)heroBtn.addEventListener('click',e=>{e.preventDefault();setFilter('marketplace',true)});
sheet.querySelector('.asset-sheet__close').addEventListener('click',closeSheet);sheet.querySelector('.asset-sheet__backdrop').addEventListener('click',closeSheet);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&sheet.classList.contains('open'))closeSheet()});
sheet.querySelector('.asset-sheet__cta').addEventListener('click',()=>{if(!current){notify('Sign-in flow is not connected in this preview');return}selected=current.key;localStorage.setItem('rwaSelectedAsset',selected);syncSelected();sheet.querySelector('.asset-sheet__cta').textContent='Selected ✓';notify(`${current.name} selected`);setTimeout(closeSheet,280)});
selBar.querySelector('button').addEventListener('click',()=>{const p=products.find(x=>x.key===selected);if(p)openProduct(p)});
const nav=qsa('.bottomnav button');function activateNav(btn){nav.forEach(x=>x.classList.remove('active'));btn.classList.add('active')}
nav.forEach((b,i)=>b.addEventListener('click',e=>{e.preventDefault();activateNav(b);if(i===0)window.scrollTo({top:0,behavior:'smooth'});if(i===1)setFilter('marketplace',true);if(i===2)setFilter('property',true);if(i===3)setFilter('games',true);if(i===4){current=null;sheet.querySelector('img').src='assets/logo-ref-exact.png';sheet.querySelector('img').alt='RWA.ms';sheet.querySelector('.asset-sheet__eyebrow').textContent='Account';sheet.querySelector('h3').textContent='Your RWA.ms account';sheet.querySelector('.asset-sheet__brand').textContent='Sign in to manage holdings and favorites.';sheet.querySelector('.asset-sheet__price').textContent='';sheet.querySelector('[data-fact="holders"]').textContent='Secure access';sheet.querySelector('[data-fact="sold"]').textContent='Portfolio ready';sheet.querySelector('.asset-sheet__cta').textContent='Continue to sign in';sheet.classList.add('open');document.body.style.overflow='hidden'}}));
syncSelected();setFilter('all',false);
})();
