(()=>{
const products=window.RWA_CATALOG||[],categories=window.RWA_CATEGORIES||[];
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
const featured=qs('.m-featured'),assets=qs('.m-assets'),tabs=qs('.m-tabs');if(!featured||!assets||!tabs)return;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SAVED_KEY='rwa_saved_assets';const readSaved=()=>{try{return JSON.parse(localStorage.getItem(SAVED_KEY)||'[]')}catch{return[]}};const writeSaved=v=>localStorage.setItem(SAVED_KEY,JSON.stringify(v));
const card=p=>`<article class="asset-card" tabindex="0" role="button" aria-label="Open ${esc(p.name)}" data-key="${p.key}" data-category="${p.category}"><div class="m-product-badge">Up to 70% Off<br>for Holders</div><button class="heart" aria-label="Save ${esc(p.name)}"><i class="fa-regular fa-heart"></i></button><img src="${p.image}" alt="${esc(p.name)}"><h4>${esc(p.name)}</h4><p>${esc(p.brand)} <span>| ${esc(p.label)}</span></p><strong>${p.price}</strong><div class="m-holder-row"><img class="m-avatar-strip" src="assets/avatars-806.png" alt="Holders"><small>${p.holders}</small></div><div class="m-sold"><i style="--p:${p.sold}%"></i><span>SOLD ${p.sold}%</span></div><button class="m-product-detail" type="button" tabindex="-1"><i class="fa-solid fa-cart-shopping"></i><span>View Details</span></button></article>`;
const representative=()=>categories.map(c=>products.find(p=>p.category===c.key)).filter(Boolean);assets.innerHTML=representative().map(card).join('');
const empty=document.createElement('div');empty.className='m-empty';empty.textContent='No assets match this filter.';featured.appendChild(empty);
let activeFilter='all-assets',selected=localStorage.getItem('rwaSelectedAsset')||'',current=null,toastTimer;
const sheet=document.createElement('div');sheet.className='asset-sheet';sheet.id='assetSheet';sheet.innerHTML=`<div class="asset-sheet__backdrop"></div><div class="asset-sheet__panel" role="dialog" aria-modal="true" aria-labelledby="assetSheetTitle"><div class="asset-sheet__grab"></div><button class="asset-sheet__close" aria-label="Close">×</button><div class="asset-sheet__hero"><img alt=""><div><div class="asset-sheet__eyebrow"></div><h3 id="assetSheetTitle"></h3><p class="asset-sheet__brand"></p><div class="asset-sheet__price"></div></div></div><div class="asset-sheet__facts"><div class="asset-sheet__fact"><small>Holders</small><b data-fact="holders"></b></div><div class="asset-sheet__fact"><small>Progress</small><b data-fact="sold"></b></div></div><button class="asset-sheet__cta">Select this asset</button></div>`;document.body.appendChild(sheet);
const selBar=document.createElement('div');selBar.className='selection-bar';selBar.innerHTML='<span></span><button type="button">View selected</button>';document.body.appendChild(selBar);const toast=document.createElement('div');toast.className='mobile-toast';document.body.appendChild(toast);
function notify(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1700)}
function productByKey(k){return products.find(p=>p.key===k)}function bindCards(){qsa('.asset-card').forEach(c=>{const key=c.dataset.key,h=c.querySelector('.heart'),saved=readSaved();if(h){const yes=saved.includes(key);h.classList.toggle('liked',yes);h.querySelector('i').className=yes?'fa-solid fa-heart':'fa-regular fa-heart'}c.addEventListener('click',e=>{if(e.target.closest('.heart'))return;if(e.target.closest('.m-product-detail')){try{window.top.location.href='product.html?asset='+encodeURIComponent(key)}catch{location.href='product.html?asset='+encodeURIComponent(key)};return}openProduct(productByKey(key))});c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProduct(productByKey(key))}});h?.addEventListener('click',e=>{e.stopPropagation();let list=readSaved();list=list.includes(key)?list.filter(x=>x!==key):[...list,key];writeSaved(list);const on=list.includes(key);h.classList.toggle('liked',on);h.querySelector('i').className=on?'fa-solid fa-heart':'fa-regular fa-heart';notify(on?'Saved to Watchlist':'Removed from Watchlist')})})}
function syncSelected(){qsa('.asset-card').forEach(c=>c.classList.toggle('selected',c.dataset.key===selected));const p=productByKey(selected);selBar.classList.toggle('show',!!p);if(p)selBar.querySelector('span').textContent=`Selected: ${p.name}`}
function openProduct(p){if(!p)return;current=p;sheet.dataset.mode='asset';sheet.querySelector('img').src=p.image;sheet.querySelector('img').alt=p.name;sheet.querySelector('.asset-sheet__eyebrow').textContent=p.label;sheet.querySelector('h3').textContent=p.name;sheet.querySelector('.asset-sheet__brand').textContent=p.brand;sheet.querySelector('.asset-sheet__price').textContent=p.price;sheet.querySelector('[data-fact="holders"]').textContent=p.holders;sheet.querySelector('[data-fact="sold"]').textContent=`${p.sold}% sold`;sheet.querySelector('.asset-sheet__cta').textContent=selected===p.key?'Selected ✓':'Select this asset';sheet.classList.add('open');document.body.style.overflow='hidden'}function closeSheet(){sheet.classList.remove('open');sheet.dataset.mode='';document.body.style.overflow=''}
function getItems(filter,query=''){let list=filter==='all-assets'?representative():products.filter(p=>p.category===filter);if(query){const q=query.toLowerCase();list=products.filter(p=>`${p.name} ${p.brand} ${p.label} ${p.category}`.toLowerCase().includes(q))}return list.slice(0,6)}
function setFilter(filter='all-assets',scroll=true){activeFilter=filter;const query=(qs('.m-search input')?.value||'').trim();const list=getItems(filter,query);assets.innerHTML=list.map(card).join('');bindCards();syncSelected();empty.classList.toggle('show',list.length===0);qsa('.m-tabs button').forEach(b=>b.classList.toggle('active',(b.dataset.value||'')===filter));if(scroll){featured.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>assets.scrollLeft=0,250)}}
qsa('.m-tabs button').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.value||'all-assets',false)));const search=qs('.m-search input');if(search){search.placeholder='Search products, AI models, apps...';search.addEventListener('input',()=>setFilter(activeFilter,false));search.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();const q=search.value.trim();try{window.top.location.href='discover.html'+(q?'?q='+encodeURIComponent(q):'')}catch{location.href='discover.html'+(q?'?q='+encodeURIComponent(q):'')}}})}
qsa('.m-verticals article').forEach(a=>{const key=a.dataset.product,btn=a.querySelector('button');btn?.addEventListener('click',e=>{e.preventDefault();try{window.top.location.href='category.html?category='+encodeURIComponent(key)}catch{location.href='category.html?category='+encodeURIComponent(key)}})});const heroBtn=qs('.m-hero button');heroBtn?.addEventListener('click',e=>{e.preventDefault();const key=heroBtn.dataset.category||'marketplace';try{window.top.location.href='category.html?category='+encodeURIComponent(key)}catch{location.href='category.html?category='+encodeURIComponent(key)}});
sheet.querySelector('.asset-sheet__close').addEventListener('click',closeSheet);sheet.querySelector('.asset-sheet__backdrop').addEventListener('click',closeSheet);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&sheet.classList.contains('open'))closeSheet()});sheet.querySelector('.asset-sheet__cta').addEventListener('click',()=>{if(sheet.dataset.mode==='account'){closeSheet();return}if(!current)return;selected=current.key;localStorage.setItem('rwaSelectedAsset',selected);syncSelected();sheet.querySelector('.asset-sheet__cta').textContent='Selected ✓';notify(`${current.name} selected`);setTimeout(closeSheet,280)});selBar.querySelector('button').addEventListener('click',()=>openProduct(productByKey(selected)));
const nav=qsa('.bottomnav button');function activate(b){nav.forEach(x=>x.classList.remove('active'));b.classList.add('active')}nav.forEach((b,i)=>b.addEventListener('click',e=>{e.preventDefault();activate(b);if(i===0)scrollTo({top:0,behavior:'smooth'});if(i===1){try{window.top.location.href='discover.html'}catch{location.href='discover.html'};return}if(i===2)qs('.m-chart-card')?.scrollIntoView({behavior:'smooth'});if(i===3)featured?.scrollIntoView({behavior:'smooth'});if(i===4)return}));
bindCards();syncSelected();setFilter('all-assets',false);
})();
